Update universalWalletConnector to include switchChain method
magiclabs/wagmi-magic-connector pull request #24
Opened 2024-04-01 21:15 UTC by robyn3choi

- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Adds the ability to switch chains when using the universal wallet connector.

- **What is the current behavior?** (You can also link to an open issue here)
Calling `switchChain` when connected with the universal wallet connector does nothing - https://github.com/magiclabs/wagmi-magic-connector/issues/22.

- **What is the new behavior (if this is a feature change)?**
Calling `switchChain` when connected with the universal wallet connector switches chains.

- **Other information**:

2025-01-31 23:44 UTC, joshuascan requested changes
Hi @ robyn3choi. Thanks for the PR!

Could you please revert the changes to the changelog.md (these will be handled by our publishing flow) as well as the changes to the package.json through line 26 (up through `prepublishOnly`)? I can then approve.

2025-02-01 22:16 UTC, ninemachines commented
Hi @joshuascan, thanks so much for this! I believe I've made the changes you're requested. Please let me know if you need anything else!

2025-02-03 18:08 UTC, joshuascan approved these changes

2025-02-03 18:08 UTC, merged

2025-02-03 18:29 UTC, joshuascan commented
@robyn3choi / @ninemachines your changes have been released in version `2.1.2`.

Thanks again for your contribution!

2025-02-03 19:55 UTC, ninemachines commented
Thanks so much, @joshuascan!!